import Head from 'next/head';
import Image from 'next/image';
import React from 'react';
import styles from '../styles/Home.module.css';
import DisplayMovies from "../components/displayMovies";

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Bookin' movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={styles.container}>
          <main className={styles.main}>
            <h1>Bookin' movies</h1>
            <h2>Most Liked</h2>
            <DisplayMovies category={"best"}></DisplayMovies>
            <h2>category</h2>
            <h3>Comedy</h3>
            <DisplayMovies category={"comedy"}></DisplayMovies>
            <h3>Horror</h3>
            <DisplayMovies category={"horror"}></DisplayMovies>
            <h3>Adventure</h3>
            <DisplayMovies category={"adventure"}></DisplayMovies>
            <h3>Action</h3>
            <DisplayMovies category={"action"}></DisplayMovies>
            <h3>Fantasy</h3>
            <DisplayMovies category={"fantasy"}></DisplayMovies>
          </main>
        </div>

      </main>
    </div>
  )
}
